In [1]:
# 2. Create a tuple called practice that has four elements: 
# ‘y’, ‘h’, ‘z’, and ‘x’.

In [2]:
practice = ('y' , 'h' , 'z' , 'x' )

In [3]:
# Q2) 3. Create a tuple named tup1 that has three elements: ‘a’, ‘b’, and ‘c’.

In [4]:
tup1 = ('a' , 'b' , 'c')

In [5]:
# Q3) 4. Provided is a list of tuples.
# Create another list called t_check that 
#contains the third element of every tuple.

In [6]:
lst_tups = [('Articuno', 'Moltres', 'Zaptos'), ('Beedrill', 'Metapod', 'Charizard', 'Venasaur', 'Squirtle'), ('Oddish', 'Poliwag', 'Diglett', 'Bellsprout'), ('Ponyta', "Farfetch'd", "Tauros", 'Dragonite'), ('Hoothoot', 'Chikorita', 'Lanturn', 'Flaaffy', 'Unown', 'Teddiursa', 'Phanpy'), ('Loudred', 'Volbeat', 'Wailord', 'Seviper', 'Sealeo')]

t_check = [] 

for tup in lst_tups:
    t_check.append(tup[2])

In [7]:
# Q4) 5. Below, we have provided a list of tuples.
#Write a for loop that saves the second element of 
#each tuple into a list called seconds.

In [8]:
tups = [('a', 'b', 'c'), (8, 7, 6, 5), ('blue', 'green', 'yellow', 'orange', 'red'), (5.6, 9.99, 2.5, 8.2), ('squirrel', 'chipmunk')]

seconds = [] 
for tup in tups:
    seconds.append(tup[1])

In [9]:
# Define a function called information that takes as input,
#the variables name, birth_year, fav_color, and hometown.
#It should return a tuple of these variables in this order.

In [10]:
def information(name , birth_year , fav_color , hometown):
    return (name , birth_year , fav_color , hometown)

In [14]:
# Define a function called info with the following 
#required parameters: name, age, birth_year,
#year_in_college, and hometown. The function should 
#return a tuple that contains all the inputted information.

In [15]:

def info(name,age,birth_year,year_in_college,hometown):
    return (name,age,birth_year,year_in_college,hometown)

In [16]:
# With only one line of code, 
# assign the variables water, fire, electric, 
#and grass to the values “Squirtle”, “Charmander”, 
#“Pikachu”, and “Bulbasaur”

In [17]:
water, fire, electric, grass = "Squirtle", "Charmander", "Pikachu", "Bulbasaur"

In [18]:
# With only one line of code, 
#assign four variables, v1, v2, v3, and v4,
#to the following four values: 1, 2, 3, 4.

In [19]:
v1 , v2 , v3 , v4 = 1 , 2 ,3 ,4

In [20]:
# If you remember, 
# the .items() dictionary method produces 
#a sequence of tuples. Keeping this in mind, 
#we have provided you a dictionary called pokemon. 
#For every key value pair, append the key to the 
#list p_names, and append the value to the list p_number. 
#Do not use the .keys() or .values() methods.

In [21]:
pokemon = {'Rattata': 19, 'Machop': 66, 'Seel': 86, 'Volbeat': 86, 'Solrock': 126}

p_names = []
p_number = []

for key , value in pokemon.items():
    p_names.append(key)
    p_number.append(value)

In [22]:
# The .items() method produces 
#a sequence of key-value pair tuples.
#With this in mind, write code to create a 
#list of keys from the dictionary track_medal_counts 
#and assign the list to the variable name track_events. 
#Do NOT use the .keys() method.

In [24]:

track_medal_counts = {'shot put': 1, 'long jump': 3, '100 meters': 2, '400 meters': 2, '100 meter hurdles': 3, 'triple jump': 3, 'steeplechase': 2, '1500 meters': 1, '5K': 0, '10K': 0, 'marathon': 0, '200 meters': 0, '400 meter hurdles': 0, 'high jump': 1}

track_events = [] 

for key , value in track_medal_counts.items():
    track_events.append(key)

In [25]:
## Assessment: Tuples

In [26]:
# Q1) Create a tuple called olympics with four elements: 
# “Beijing”, “London”, “Rio”, “Tokyo”.

In [27]:
olympics = ("Beijing", "London", "Rio", "Tokyo")

In [28]:
# Q2) The list below, tuples_lst, is a list of tuples.
# Create a list of the second elements of each tuple
#and assign this list to the variable country.

In [29]:
tuples_lst= [('Beijing', 'China', 2008), ('London', 'England', 2012), ('Rio', 'Brazil', 2016, 'Current'), ('Tokyo', 'Japan', 2020, 'Future')]

country = [] 
for tup in tuples_lst:
    print(tup)
    country.append(tup[1])

('Beijing', 'China', 2008)
('London', 'England', 2012)
('Rio', 'Brazil', 2016, 'Current')
('Tokyo', 'Japan', 2020, 'Future')

In [30]:
# Q2) With only one line of code, 
#assign the variables city, country, 
#and year to the values of the tuple olymp.

In [31]:

olymp = ('Rio', 'Brazil', 2016)
city, country, year = olymp

In [32]:
# Q3 ) Define a function called info
# with five parameters: name, gender, age, bday_month,
#and hometown. The function should then return 
#a tuple with all five parameters in that order.

In [33]:
def info(name , gender , age , bday_month , hometown):
    return (name , gender , age , bday_month , hometown)

In [34]:
# Q4) Given is the dictionary,
# gold, which shows the country and the number of gold medals
#they have earned so far in the 2016 Olympics. 
#Create a list, num_medals, that contains only 
#the number of medals for each country. You must use the 
#.items() method. Note: The .items() method provides a
#list of tuples. Do not use .keys() method.

In [35]:
gold = {'USA':31, 'Great Britain':19, 'China':19, 'Germany':13, 'Russia':12, 'Japan':10, 'France':8, 'Italy':8}

num_medals = [] 

for key , value in gold.items() : 
    num_medals.append(value)